### ISSUE TITLE
As a colour-blind user, I want the application to be designed with colour-blind users in mind.

### ISSUE THREAD

**Issue by claudiiafg** [claudiiafg/MapConU#150]
A colour-blind user should be able to use the application like a regular user and have a similar user experience.

**Comment by tedgag** [comment]
To ensure that our application would be suitable for colour-blind users, we have made a few design decisions that would facilitate the user experience for users affected by colour-blindness

- All the buttons have images instead of text
- We try to distinguish overlapping elements by shape or symbol rather than colour
- We only use one colour (Concordia red) with black and white for our User Interface

There are many types of colour-blindness, but in general, colour-blind individual have difficulties distinguishing between tones (ex: green and red). By using only a few tones or variations of a tone, we then reduce this problem. Also, by using images and symbols, we reduce the importance of colour in our user experience, which also can also help.

We have tested the usability of our application using a colour blindness simulator called Color Oracle: https://colororacle.org/. This application allows us to set a filter to see what our application looks like from the point of view of a colour blind user. Here are a few screenshots of our application taken with the most common colour blindness filters:

<img width="379" alt="Screen Shot 2020-03-28 at 2 08 06 PM" src="https://user-images.githubusercontent.com/36055308/77830234-8fcf8480-70fd-11ea-920d-6910d622e345.png">

<img width="378" alt="Screen Shot 2020-03-28 at 2 08 38 PM" src="https://user-images.githubusercontent.com/36055308/77830247-a2e25480-70fd-11ea-9c1e-48ef278ed38e.png">

<img width="376" alt="Screen Shot 2020-03-28 at 2 09 13 PM" src="https://user-images.githubusercontent.com/36055308/77830259-b7bee800-70fd-11ea-9f35-03139a04ae17.png">

<img width="376" alt="Screen Shot 2020-03-28 at 2 10 26 PM" src="https://user-images.githubusercontent.com/36055308/77830282-e2a93c00-70fd-11ea-8e64-ce495052d140.png">

<img width="376" alt="Screen Shot 2020-03-28 at 2 11 00 PM" src="https://user-images.githubusercontent.com/36055308/77830295-f5bc0c00-70fd-11ea-8926-80ba8f1b782f.png">

<img width="375" alt="Screen Shot 2020-03-28 at 2 11 15 PM" src="https://user-images.githubusercontent.com/36055308/77830305-0076a100-70fe-11ea-9278-1348a30ae2db.png">
