### ISSUE TITLE
As a user, I want to be able to run the application on an Android or iOS tablet

### ISSUE THREAD

**Issue by tedgag** [claudiiafg/MapConU#215]
The user should be able to use the application on their tablet with the same functionalities as the phone application.

**Comment by tedgag** [comment]
Already implemented but need further testing before closing

**Comment by GwenLegate** [comment]
Installed the app on my tablet and did a quick test of features.  

The App loads and the buildings are highlighted but I think there is something off with the Google maps because I can't use the outdoor pois or the map directions and if I manually scroll over to my apartment address, the blue dot indicating my location isn't there (I made sure to allow the app to access location services).
The selection to loyola campus doesn't work either.

You can go inside and the indoor directions work, so do the indoor pois on both H8 anf H9.  The back botton to go outside also works.

Settings button works so does the translation functionality and the source code links.

There's some css spacing issues as well but I think the google map is the main trouble.  I'm going to try to figure out how to enable the debugging mode for the tablet and try to get more specific info about if it's my tablet settings or something else.

**Comment by achung98** [comment]
Could it be the android version of the tablet ?

**Comment by GwenLegate** [comment]
Maybe, it's old, old enough I'm kind of surprised it still works and isn't the fanciest.  Looking at the device info:  Galaxy Tab A, Android version: 5.0.2.  That might be an issue

**Comment by GwenLegate** [comment]
Fix:  apparently using my tablet at 2% battery turns off location services.  Maps functionality works well.  The only issues with the tablet are some css bugs.  bug issues pending...

**Comment by GwenLegate** [comment]
closing this issue because we've established that the App works on a tablet with no specific tablet issues except for that the css bugs are more obvious.
