### ISSUE TITLE
Add mouse-over building information box

### ISSUE THREAD

**Issue by tedgag** [claudiiafg/MapConU#94]
Add pop-up when clicking Concordia buildings.

https://www.figma.com/file/GWTIDHydeRLSbnt2GM9qF5/MapConU?node-id=39%3A12

<img width="153" alt="Screen Shot 2020-02-26 at 10 01 08 PM" src="https://user-images.githubusercontent.com/36055308/75408352-81663100-58e3-11ea-8186-541251f4f7aa.png">

**Comment by GwenLegate** [comment]
Link to mockup screen for this feature:

![buildingDsc](https://user-images.githubusercontent.com/46829100/75350427-8049eb00-5874-11ea-9f97-ce6c5e9c3244.JPG)

**Comment by GwenLegate** [comment]
The issues for implementing the box info and the indoor routing need to be separated.  There is a separate issue for indoor routing.  The focus of this issue is the complete implementation of outdoor features and routing to a placeholder view of the indoors.  Additional routing can take place as indoor views are implemented
